services:
  postgres:
    image: postgres:16-alpine
    environment: 
      POSTGRES_USER: pasarpixel
      POSTGRES_PASSWORD: pasarpixel
      POSTGRES_DB: pasarpixel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



  auth-service:
    build: 
      context: ../../services/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - ../../services/auth-service/.env
    environment:
      DATABASE_URL: postgresql://pasarpixel:pasarpixel@postgres:5432/pasarpixel

  client: 
    build:
      context: ../../client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
    
volumes:
  postgres_data: